### ISSUE TITLE
MacOS version 

### ISSUE THREAD

**Issue by kernelism** [Xoloth/Dell-G3-3500-Opencore-Hackintosh#2]
You didn't specify what MacOS **version** you installed. Just wanted to know cause BigSur isn't working as mentioned in your readme.

**Comment by Xoloth** [comment]
At the time of this repos last update, Catalina was the latest version of macOS. You can use this as a base for your Big Sur or newer installation or you can use Catalina.

**Comment by kernelism** [comment]
Umm thanks for the info! I have some issues with making it work. Would you mind taking a peek?

**Comment by Xoloth** [comment]
I would love to help but as in readme I no longer have this device and I also lost interest in hackintosh thus I am unable to help you any further.

**Comment by kernelism** [comment]
Ah that's totally understandable. Thanks for considering!
